### ISSUE TITLE
[Maybe a bug] Relays names didn't show when exists a double

### ISSUE THREAD

**Issue by serrq** [KoalaSat/nostros#279] opened 2023-02-08 14:31 UTC
![Screenshot_2023-02-08-15-26-06-28_5c73a23a736fb25cbee05f6b3c0a142a (1)](https://user-images.githubusercontent.com/113377431/217558488-5c59e556-58af-4348-ad9d-a3201cec9caf.jpg)

Is possible add also "edit" to relay's buttons?

![Screenshot_2023-02-08-15-26-32-68_5c73a23a736fb25cbee05f6b3c0a142a (1)](https://user-images.githubusercontent.com/113377431/217558674-a0957ed5-ae3c-45c6-88d6-f895c5b4c135.jpg)

**Comment by KoalaSat** [comment] 2023-02-08 18:26
Looks like a bug yes, Can you explain step by step how to reproduce this?

**Comment by KoalaSat** [comment] 2023-02-08 19:39
Thank you!

**Comment by KoalaSat** [comment] 2023-02-09 22:45
Fixed with https://github.com/KoalaSat/nostros/releases/tag/v0.2.2.7-alpha

**Closed** 2023-02-11 19:12 UTC
Labels: bug, javascript, ready to release
